pool_default_size: 2
journal_size: 1000
monitor_interface: "{{ ansible_default_ipv4.interface }}"
monitor_address: "{{ ansible_default_ipv4.address }}"
public_network: "{{ ansible_default_ipv4.network }}/24"
common_single_host_mode: true
openstack_config: true
ceph_origin: distro
ceph_conf_overrides:
  global:
    osd pool default size: 2
    osd pool default min size: 1
