python3 from powerline.vim import setup as powerline_setup
python3 powerline_setup()
python3 del powerline_setup
set laststatus=2
set t_Co=256


syntax enable
set background=dark
colorscheme solarized

execute pathogen#infect()

set mouse=a
