---

- hosts: sut
  roles:
    - kolla-aio
  become: true
  become_method: sudo
  vars:
    playbook_root: "/root"
    kolla_ansible_directory: "{{ playbook_root }}/kolla-ansible"
    kolla_host: "{{ ansible_default_ipv4.address }}"
    kolla_external_if: ens2

  tasks:

  - name: check-out kolla into {{ kolla_ansible_directory }}
    git:
      repo: https://github.com/openstack/kolla.git
      dest: "{{ kolla_ansible_directory }}"
      force: yes

...
