---

- hosts: sut
  roles:
    - container-host
    - kolla-aio
  become: true
  become_method: sudo
  vars:
    playbook_root: "/root"
    kolla_ansible_directory: "{{ playbook_root }}/kolla-ansible"
    kolla_host: 192.168.100.158
    kolla_external_if: eno1

  tasks:

  - name: check-out kolla into {{ kolla_ansible_directory }}
    git: 
      repo: https://github.com/openstack/kolla.git
      dest: "{{ kolla_ansible_directory }}"
      force: yes
 
...
