---

- hosts: localhost
  vars:
    playbook_root: "{{ playbook_dir }}/../"
    ceph_ansible_directory: "{{ playbook_root }}/ceph-ansible"
    ceph_host: 192.168.100.180
    ceph_frontend: 192.168.100.180
    ceph_subnet: 24
    ceph_interface: ens3
    ceph_disks:
      - /dev/vdb
      - /dev/vdc

  tasks:

  - name: check-out ceph-ansible into {{ playbook_root }}
    git: 
      repo: https://github.com/ceph/ceph-ansible.git
      dest: "{{ceph_ansible_directory}}"
      force: yes

  - name: define ceph-ansible host inventory path
    lineinfile:
      create: yes
      dest: "{{ceph_ansible_directory}}/ansible.cfg"
      line: "inventory = hosts"
 
  - name: create ceph-ansible host inventory
    blockinfile:
      create: yes
      dest: "{{ceph_ansible_directory}}/hosts"
      block: |
        [ceph-aio-host]
        {{ ceph_host }}
        [mons:children]
        ceph-aio-host
        [osds:children]
        ceph-aio-host

  - name: create cluster deployment config file
    blockinfile:
      create: yes
      dest: "{{ceph_ansible_directory}}/group_vars/all"
      block: |
        pool_default_size: 2
        journal_size: 1000
        monitor_interface: {{ ceph_interface }}
        monitor_address: {{ ceph_frontend }}
        public_network: {{ ceph_frontend }}/{{ ceph_subnet }}
        common_single_host_mode: true
        ceph_origin: distro
        ceph_conf_overrides:
         global:
           osd pool default size: 2
           osd pool default min size: 1


  - name: create osd deployment config file
    blockinfile:
      create: yes
      dest: "{{ceph_ansible_directory}}/group_vars/osds"
      block: |
        journal_collocation: true
        devices:
          {% for ceph_disk in ceph_disks %}
            - {{ ceph_disk }}
          {% endfor %}

  - name: create ansible-ceph playbook
    blockinfile:
      create: yes
      dest: "{{ceph_ansible_directory}}/{{ ceph_host }}.yml"
      block: |
        - hosts: ceph-aio-host
          become: True
          roles:
          - ceph-mon
          - ceph-osd

...
