---

- hosts: workstation
  vars:
    - container_deployment_scenario: docker_on_devicemapper_vg
    - dm_docker_vg: vg_nvme
    - kolla_host: "{{ ansible_default_ipv4.address }}"
    - kolla_external_bridge_cidr: 192.168.200.1/24
    - kolla_external_veth_cidr: 192.168.200.2/24
    - kolla_vip: 192.168.100.200
  roles:
        - { name: base-system, tags: base-system }
        - { name: virtualization-host, tags: virtualization-host }
        - { name: workstation, tags: workstation }
        - { name: container-host, tags: container-host }
        - { name: ceph.ceph-mon, tags: ceph }
        - { name: ceph.ceph-osd, tags: ceph }
        - { name: kolla-aio, tags: kolla }

...
