---

- hosts: sut
  vars:
    - cli_environment: true
    - perf_utilities: true
    - sublime: false
    - py_charm: false
    - workstation_primary_cidr: 192.168.100.80/24
    - workstation_primary_gw: 192.168.100.1
    - workstation_primary_netif: ens3
  roles:
        - { name: base-system, tags: base-system }
        - { name: virtualization-host, tags: virtualization-host }
        - { name: workstation, tags: workstation }

...
