---

- hosts: workstation
  vars:
    - container_deployment_scenario: docker_on_devicemapper_vg
    - dm_docker_vg: vg_nvme
    - kolla_host: "{{ ansible_default_ipv4.address }}"
    - kolla_network_scenario: second_interface
    # - kolla_external_bridge_cidr: 192.168.178.201/24
    # - kolla_external_veth_cidr: 192.168.200.2/24
    # - kolla_external_bridge_ip: 192.168.200.1
    # - kolla_external_pool_start: 192.168.200.3
    # - kolla_external_pool_end: 192.168.200.254
    - kolla_external_interface: enp6s0
    - kolla_external_interface_ip: 192.168.178.201/24
  roles:
        - { name: base-system, tags: base-system }
        - { name: virtualization-host, tags: virtualization-host }
        - { name: workstation, tags: workstation }
        - { name: container-host, tags: container-host }
        - { name: ceph.ceph-mon, tags: ceph }
        - { name: ceph.ceph-osd, tags: ceph }
        - { name: kolla-aio, tags: kolla }

...
