---

- include: ./prerequisites/fedora_prerequisites.yml
  when: ansible_os_family == "RedHat" and ansible_distribution == "Fedora"

- include: ./nvidia-driver.yml
  tags: nvidia-driver

- include: network-config.yml

...
