---

- name: configure network adapter profile for {{ workstation_primary_netif }}
  nmcli:
    ifname: "{{ workstation_primary_netif }}"
    conn_name: "{{ workstation_primary_netif }}"
    ip4: "{{ workstation_primary_cidr }}"
    dns4: "{{ workstation_primary_dns }}"
    gw4: "{{ workstation_primary_gw }}"
    type: ethernet
    state: present

- name: disable dhcp network adapter {{ workstation_primary_netif }}
  shell: nmcli connection modify {{ workstation_primary_netif }} ipv4.method manual

- name: set route metric to 100 in {{ workstation_primary_netif }}
  shell: nmcli connection modify {{ workstation_primary_netif }} ipv4.route-metric 100

- name: set system hostname
  hostname: name={{ system_fqdn }}

- name: ensure local hostname resolution
  lineinfile:
    dest: /etc/hosts
    line: "{{ workstation_primary_ip4 }} {{ system_fqdn }} {{ system_hostname }}"

...
