---

- name: download PyCharm community edition
  get_url:
    url: https://download.jetbrains.com/python/pycharm-community-2016.2.3.tar.gz
    checksum: "sha256:8ea07f6ff9f63a56cd6c779a3b1727157e177c2c4da8c056dec60b056e03f05a"
    dest: /tmp

- name: install PyCharm into {{ pycharm_install_root }}
  unarchive:
    src: /tmp/pycharm-community-2016.2.3.tar.gz
    dest: "{{ pycharm_install_root }}"

...