---

- name: install libvirt environment
  package: name={{ item }} state=present
  with_items:
        - libvirt-daemon
        - libvirt-daemon-kvm
        - libvirt-daemon-config-network
        - libvirt-daemon-driver*
        - qemu-img
        - qemu-kvm
        - virt-manager
        - virt-install
        - libguestfs-tools
        - libguestfs-bash-completion

- name: start and enable libvirtd
  service: name=libvirtd state=started enabled=yes

...
