---
- name: install kolla dependencies on fedora
  package: name={{ item }} state=present
  with_items:
    - python-pip
    - python-devel
    - libffi-devel
    - gcc
    - openssl-devel
    - python-docker-py
    - redhat-rpm-config
    - ansible
  notify:
    - reinstall python3-pip

- name: install openstack clients on fedora
  package: name={{ item }} state=present
  with_items:
    - python-openstackclient
    - python-neutronclient

- name: create kolla docker config directory
  file: path=/etc/systemd/system/docker.service.d state=directory

- name: ensure MountFlags on docker
  copy: src=kolla.conf dest=/etc/systemd/system/docker.service.d/kolla.conf
  notify:
    - reload systemd
    - restart docker

- name: install shade via pip
  pip: name=kolla state=present

...
