---
- name: install kolla dependencies on fedora
  package: name={{ item }} state=present
  with_items:
    - python-pip
    - python-devel
    - libffi-devel
    - gcc
    - openssl-devel
    - python-docker-py
    - redhat-rpm-config
    - ansible

- name: install openstack clients on fedora
  package: name={{ item }} state=present
  with_items:
    - python-openstackclient
    - python-neutronclient
...
