---

- include: ./installs/tmux_on_fedora.yml
  when: 
    - ansible_os_family == 'RedHat'
    - ansible_distribution == 'Fedora'

- include: ./installs/powerline_on_fedora.yml
  when: 
    - ansible_os_family == 'RedHat'
    - ansible_distribution == 'Fedora'

- name: set tmux.conf
  copy: src=tmux.conf dest=/root/.tmux.conf

- name: create powerline tmux colorschemes directory
  file: path=/root/.config/powerline/colorschemes/tmux/ state=directory

- name: create powerline tmux themes directory
  file: path=/root/.config/powerline/themes/tmux/ state=directory

- name: set powerline color theme
  copy: remote_src=True src=/etc/xdg/powerline/colorschemes/tmux/solarized.json dest=/root/.config/powerline/colorschemes/tmux/default.json

- name: set powerline tmux group colors
  copy: src=tmux-powerline-groups.json dest=/root/.config/powerline/colorschemes/tmux/default.json

- name: set powerline tmux segments
  copy: src=tmux-powerline-theme.json dest=/root/.config/powerline/themes/tmux/default.json

- name: create powerline vim themes directory
  file: path=/root/.config/powerline/themes/vim/ state=directory

- name: set powerline vim layout
  copy: src=tmux-vim-theme.json dest=/root/.config/powerline/themes/vim/default.json

- name: patch powerline mem segment
  patch: src=mem_usage.patch dest='/usr/lib/python3.5/site-packages/powerlinemem/mem_usage.py'

- name: create vim autoload
  file: path=/root/.vim/autoload state=directory

- name: install vim pathogen
  get_url: url=https://tpo.pe/pathogen.vim dest=/root/.vim/autoload/pathogen.vim

- name: create vim bundle
  file: path=/root/.vim/bundle state=directory

- name: install vim nerdtree
  git: repo=https://github.com/scrooloose/nerdtree.git dest=/root/.vim/bundle/nerdtree

- name: install vim nerdtree git plugin
  git: repo=https://github.com/Xuyuanp/nerdtree-git-plugin.git dest=/root/.vim/bundle/nerdtree-git-plugin

- name: create vim colors
  file: path=/root/.vim/colors state=directory

- name: set vim colors
  copy: src=solarized.vim dest=/root/.vim/colors/solarized.vim

- name: set bashrc
  copy: src=bashrc dest=/root/.bashrc

- name: set vimrc
  copy: src=vimrc dest=/root/.vimrc

- name: set dir_colors
  copy: src=dir_colors dest=/root/.dir_colors
...
