---

- name: install basic packages
  package: name={{ item }} state=present
  with_items:
      - wget
      - curl
      - vim
      - bash-completion
      - NetworkManager
      - bind-utils
      - procps-ng
      - net-tools

- include: perf-utilities.yml
  when:
    - perf_utilities is defined
    - perf_utilities

- include: cli-environment.yml
  when:
    - cli_environment is defined
    - cli_environment

...
