---

- name: install basic packages
  package: name={{ item }} state=present
  with_items:
      - wget
      - curl
      - vim
      - bash-completion
      - NetworkManager
      - bind-utils
      - procps-ng
      - net-tools

- include: perf-utilities.yml
  tags:
    - perf-utilities

- include: cli-environment.yml
  tags:
    - cli-environment

...
