---

- name: enable device mapper docker storage setup
  lineinfile: dest=/etc/sysconfig/docker-storage-setup line=STORAGE_DRIVER="devicemapper"

- name: make sure a block device for device mapper was chosen
  fail:
   msg: "please choose an block device for dockers device mapper volume"
  when: dm_docker_device is not defined

- name: enable device mapper device in docker storage setup
  lineinfile: dest=/etc/sysconfig/docker-storage-setup line=DEVS={{ dm_docker_device }}

- name: run docker storage configurator
  shell: docker-storage-setup
  notify:
    - restart docker

...