- name: run kolla prechecks
  shell: kolla-ansible prechecks

- name: download kolla images
  shell: kolla-ansible pull

- name: run kolla deployment
  shell: kolla-ansible deploy

- name: run kolla post-deployment
  shell: kolla-ansible post-deploy
