- name: create kolla config directory
  file: path=/etc/kolla state=directory

- name: create kolla config
  template: src=globals.yml.j2 dest=/etc/kolla/globals.yml

- name: create empty passwords.yml
  copy: remote_src=yes src=/usr/share/kolla-ansible/etc_examples/kolla/passwords.yml dest=/etc/kolla/passwords.yml force=no
  register: passwords_empty

- name: auto-generate passwords
  shell: kolla-genpwd
  when: passwords_empty.changed

- name: fetch kolla passwords into fetch directory
  fetch: src=/etc/kolla/passwords.yml dest=fetch/ flat=yes

- name: load openstack credentials from kolla config
  include_vars: fetch/passwords.yml

- name: create glance config directory
  file: path=/etc/kolla/config/glance state=directory

- name: create glance-api.conf
  template: src=glance-api.conf.j2 dest=/etc/kolla/config/glance/glance-api.conf

- name: copy ceph.conf to glance config directory
  copy: remote_src=yes src=/etc/ceph/ceph.conf dest=/etc/kolla/config/glance/ceph.conf

- name: copy glance keyring to glance config directory
  copy: remote_src=yes src=/etc/ceph/ceph.client.glance.keyring dest=/etc/kolla/config/glance/ceph.client.glance.keyring

- name: create glance client configuration
  ini_file: section=client.glance option=keyring value=/etc/ceph/ceph.client.glance.keyring state=present dest=/etc/kolla/config/glance/ceph.conf

- name: create cinder config directory
  file: path=/etc/kolla/config/cinder state=directory

- name: create cinder-volume.conf
  template: src=cinder-volume.conf.j2 dest=/etc/kolla/config/cinder/cinder-volume.conf

- name: copy ceph.conf to cinder config directory
  copy: remote_src=yes src=/etc/ceph/ceph.conf dest=/etc/kolla/config/cinder/ceph.conf

- name: create cinder-volume config directory
  file: path=/etc/kolla/config/cinder/cinder-volume state=directory

- name: create cinder-backup config directory
  file: path=/etc/kolla/config/cinder/cinder-backup state=directory

- name: copy cinder keyring to cinder-volume config directory
  copy: remote_src=yes src=/etc/ceph/ceph.client.cinder.keyring dest=/etc/kolla/config/cinder/cinder-volume/ceph.client.cinder.keyring

- name: copy cinder keyring to cinder-backup config directory
  copy: remote_src=yes src=/etc/ceph/ceph.client.cinder.keyring dest=/etc/kolla/config/cinder/cinder-backup/ceph.client.cinder.keyring

- name: create cinder client configuration
  ini_file: section=client.cinder option=keyring value=/etc/ceph/ceph.client.cinder.keyring state=present dest=/etc/kolla/config/cinder/ceph.conf

- name: create cinder-backup client configuration
  ini_file: section=client.cinder-backup option=keyring value=/etc/ceph/ceph.client.cinder-backup.keyring state=present dest=/etc/kolla/config/cinder/ceph.conf

- name: create cephx nova user
  shell: ceph auth get-or-create client.nova mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool=volumes, allow rwx pool=vms, allow rx pool=images'
  register: nova_user_create

- name: create cephx nova user keyring
  shell: ceph auth get client.nova > /etc/ceph/ceph.client.nova.keyring

- name: create cephx nova user keyring
  file:
    dest: /etc/ceph/ceph.client.nova.keyring
    mode: u=rw
    owner: ceph
    group: ceph
    state: file

- name: create nova config directory
  file: path=/etc/kolla/config/nova state=directory

- name: create nova-compute.conf
  template: src=nova-compute.conf.j2 dest=/etc/kolla/config/nova/nova-compute.conf

- name: copy ceph.conf to nova config directory
  copy: remote_src=yes src=/etc/ceph/ceph.conf dest=/etc/kolla/config/nova/ceph.conf

- name: copy nova keyring as nova keyring to nova config directory
  copy: remote_src=yes src=/etc/ceph/ceph.client.nova.keyring dest=/etc/kolla/config/nova/ceph.client.nova.keyring

- name: copy cinder keyring as nova keyring to nova config directory
  copy: remote_src=yes src=/etc/ceph/ceph.client.cinder.keyring dest=/etc/kolla/config/nova/ceph.client.cinder.keyring

- name: create nova client configuration for nova
  ini_file: section=client.nova option=keyring value=/etc/ceph/ceph.client.nova.keyring state=present dest=/etc/kolla/config/nova/ceph.conf

- name: create cinder client configuration for nova
  ini_file: section=client.cinder option=keyring value=/etc/ceph/ceph.client.cinder.keyring state=present dest=/etc/kolla/config/nova/ceph.conf
