---

- include: ./uplink_bridge.yml

- include: ./system_config.yml

- include: ./installs/fedora_prerequisites.yml
  when: ansible_os_family == "RedHat" and ansible_distribution == "Fedora"

- include: ./installs/kolla_via_pip.yml
  when: ansible_os_family == "RedHat" and ansible_distribution == "Fedora"

- include: ./kolla_config.yml



...
