---

- include: ./uplink_bridge.yml

- include: ./system_config.yml

- include: ./installs/fedora_prerequisites.yml
  when: ansible_os_family == "RedHat" and ansible_distribution == "Fedora"

- include: ./installs/centos_prerequisites.yml
  when: ansible_os_family == "RedHat" and ansible_distribution == "CentOS"

- include: ./installs/kolla_via_pip.yml

- include: ./kolla_config.yml

- meta: flush_handlers

- name: run kolla prechecks
  shell: kolla-ansible prechecks

- name: download kolla images
  shell: kolla-ansible pull

- name: run kolla deployment
  shell: kolla-ansible deploy

...
