---

- include: ./installs/fedora_prerequisites.yml
  when: ansible_os_family == "RedHat" and ansible_distribution == "Fedora"

- include: ./installs/centos_prerequisites.yml
  when: ansible_os_family == "RedHat" and (ansible_distribution == "CentOS" or ansible_distribution == "RedHat")

- include: ./uplink_bridge.yml

- include: ./system_config.yml

- include: ./installs/kolla_via_pip.yml

- include: ./kolla_config.yml

- meta: flush_handlers

- include: ./kolla_deploy.yml

- include: ./openstack_bootstrap.yml

...
