---

- name: undefine existing libvirt bridge named 'external'
  virt_net:
    name: external
    state: absent

- name: create local libvirt bridge named 'external' for openstack uplink network
  virt_net: 
   command: define
   name: external
   xml: '{{ lookup("template", "external_bridge.xml.j2") }}'
  notify:
    - start external network bridge

- name: set libvirt bridge to autostart
  virt_net:
    autostart: 'yes'
    name: external

- name: create local veth pair
  copy: src=roles/workstation/files/25-veth-pair.netdev dest=/etc/systemd/network/25-veth-pair.netdev
  notify:
    - restart systemd-networkd

- name: add veth end to libvirt bridge
  copy: src=roles/workstation/files/26-bridge-slave-interface.network dest=/etc/systemd/network/26-bridge-slave-interface.network
  notify:
    - restart systemd-networkd

- name: start veth
  copy: src=roles/workstation/files/27-veth-end.network dest=/etc/systemd/network/27-veth-end.network
  notify:
    - restart systemd-networkd

- name: enable NetworkManager-wait-online.service
    service: name=NetworkManager-wait-online.service state=enabled
  
- name: set systemd-networkd.service to start after virbr-ex is up
  copy: src=roles/workstation/files/systemd-networkd.service dest=/etc/systemd/system/systemd-networkd.service

handlers:

- name: start external network bridge
  virt_net:
    name: external
    state: active

- name: restart systemd-networkd
  service: name=systemd-networkd state=restarted enabled='yes'

...