---

- name: set selinux to permissive
  selinux: state=permissive

- name: enable libvirt for containerized systemd workaround
  service: name=libvirtd state=stopped enabled=yes

- name: create stop libvirt for containerized systemd workaround
  copy: src=stop-libvirtd.service dest=/etc/systemd/system/stop-libvirtd.service
  notify:
    - reload systemd
    - enable stop-libvirtd
...
