---

- name: set selinux to permissive
  selinux: state=permissive policy=targeted

- name: enable libvirt for containerized systemd workaround
  service: name=libvirtd state=stopped enabled=yes
  
...
