---

- name: restart systemd-networkd
  service: name=systemd-networkd state=restarted enabled=yes

- name: restart systemd-resolved
  service: name=systemd-resolved state=restarted enabled=yes

- name: enable stop-libvirtd
  service: name=stop-libvirtd state=started enabled=yes

...
